name: docker-image
# trigger
on:
  push:
    branches: ["stage"]
env:
  REGISTRY: antgonto
  IMAGE_NAME: kubelabs_publicapi
  OPS_BRANCH: master
  OPS_REPO: antgonto/dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get TAG Version
        run: echo "RELEASE_VERSION=$(git tag --sort=-creatordate | head -1)" >> $GITHUB_ENV
      - name: Show new tag
        run: |
          echo ${{ env.RELEASE_VERSION }}
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          # Comment for commit
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
          build-args: |
            APP_ENV=${{ secrets.APP_ENV }}

#      - name: test
#        run: docker run --rm --name api -p 3000:3000 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
