name: docker-image

# trigger
on:
  push:
    branches: ["stage"]

env:
  REGISTRY: antgonto
  IMAGE_NAME: kubelabs_publicapi
  OPS_BRANCH: master
  OPS_REPO: antgonto/dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
